export const quiz = {
  totalQuestions: 3,
  questions: [
    {
      id: 1,
      question: "Quel-est mon manga préféré ?",
      answers: [
        "B E R S E R K",
        "Fullmetal Alchemist",
        "A K I R A",
        "20th Century Boys",
      ],
      correctAnswer: 1,
      severalAnswer: false,
    },
    {
      id: 2,
      question: "Je suis team : ",
      answers: ["LEGO", "Mécano", "KAPLA", "Rien, c'est pour les gamins."],
      correctAnswer: 0,
      severalAnswer: false,
    },
    {
      id: 3,
      question: "Mon jeu préféré, c'est : ",
      answers: [
        "Dark Souls",
        "Hollow Knight",
        "The Witcher 3",
        "The Last of Us",
      ],
      correctAnswer: 3,
      severalAnswer: false,
    },
    {
      id: 4,
      question: "Mon chat s'appelle",
      answers: ["Chouquette", "Merguez", "Jean-Jacques", "Salsa"],
      correctAnswer: 2,
      severalAnswer: false,
    },
    {
      id: 5,
      question: "j'écoute principalement du : ",
      answers: ["The Police", "Sum 41", "Taylor Swift", "Aya Nakamura"],
      correctAnswer: 1,
      severalAnswer: false,
    },
    {
      id: 6,
      question: "Je tiens bien l'alcool",
      answers: [
        "Mytho",
        "Je suis increvable",
        "Une goutte, je suis au sol",
        "Au mental, mais je résiste",
      ],
      correctAnswer: 3,
      severalAnswer: false,
    },
    {
      id: 7,
      question: "Boisson préféré",
      answers: ["Ice Tea", "Coca Cola", "Perrier", "Je bois que de l'eau"],
      correctAnswer: 0,
      severalAnswer: false,
    },
    {
      id: 8,
      question: "Ma série préféré",
      answers: [
        "Stranger Things",
        "Breaking Bad",
        "Peaky Blinders",
        "Game of Thrones",
      ],
      correctAnswer: 1,
      severalAnswer: false,
    },
    {
      id: 9,
      question: "Mon sport de coeur",
      answers: ["Tennis", "Soccer", "Basketball", "Je fais un peu de tout"],
      correctAnswer: 3,
      severalAnswer: false,
    },
    {
      id: 10,
      question: "A la neige, je pratique le :",
      answers: ["Ski", "Wingsut", "Snowboard", "Tire-fesses"],
      correctAnswer: 2,
      severalAnswer: false,
    },
    {
      id: 11,
      question: "Ma marque de fringue préféré",
      answers: ["Van's", "Carhartt", "Tommy", "Adidas"],
      correctAnswer: 1,
      severalAnswer: false,
    },
    {
      id: 12,
      question: "Je n'ai jamais posé le pied dans ce pays",
      answers: ["Canada", "Etats-Unis", "Japon", "Italie"],
      correctAnswer: 2,
      severalAnswer: false,
    },
  ],
};
