import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const inter = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-slate-100 min-h-screen h-full">
          <div className="pt-20 flex flex-col items-center">
            <h1 className="text-6xl font-bold my-5">
              Quiz<span className="text-green-400">1</span>max
            </h1>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
